name: Backend CD - Deploy to AKS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Backend CI - Test, Build and Push Images to ACR"]
    types:
      - completed

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: week08-aks
          resource-group: week08-rg

      - name: Deploy Backend Services
        run: |
          IMAGE_TAG=${{ github.sha }}-${{ github.run_id }}
          ACR=${{ secrets.ACR_LOGIN_SERVER }}

          echo "🔧 Updating Kubernetes manifests with $IMAGE_TAG"

          sed -i "s|image: .*/product_service:.*|image: $ACR/product_service:$IMAGE_TAG|" ./k8s/product-deployment.yaml
          sed -i "s|image: .*/order_service:.*|image: $ACR/order_service:$IMAGE_TAG|" ./k8s/order-deployment.yaml

          kubectl apply -f ./k8s/product-deployment.yaml
          kubectl apply -f ./k8s/order-deployment.yaml
