name: Frontend CD - Deploy to AKS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Frontend CI - Build and Push Images to ACR"]
    types:
      - completed

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: week08-rg
          cluster-name: week08-aks
          subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Frontend
        run: |
          IMAGE_TAG=${{ github.sha }}-${{ github.run_id }}
          ACR=${{ secrets.ACR_LOGIN_SERVER }}

          echo "🔧 Updating frontend manifest with $IMAGE_TAG"

          sed -i "s|image: .*/frontend:.*|image: $ACR/frontend:$IMAGE_TAG|" ./k8s/frontend.yaml

          kubectl apply -f ./k8s/frontend.yaml
