name: Frontend CI - Build and Push Images to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Frontend
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}
        run: |
          echo "🚀 Building frontend image..."
          docker build -t $ACR_LOGIN_SERVER/frontend:$IMAGE_TAG ./frontend
          echo "✅ Pushing versioned tag: $IMAGE_TAG"
          docker push $ACR_LOGIN_SERVER/frontend:$IMAGE_TAG

          echo "✅ Tagging and pushing 'latest'"
          docker tag $ACR_LOGIN_SERVER/frontend:$IMAGE_TAG $ACR_LOGIN_SERVER/frontend:latest
          docker push $ACR_LOGIN_SERVER/frontend:latest

      - name: Logout
        run: az logout
        if: always()
