name: Frontend CI - Build and Push Images to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Frontend
        run: |
          echo "🚀 Building frontend image..."
          docker build ./frontend -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}-${{ github.run_id }}

          echo "✅ Pushing versioned tag"
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}-${{ github.run_id }}

          echo "✅ Tagging and pushing 'latest'"
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}-${{ github.run_id }} ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout
        run: az logout
        if: always()
