name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_NAME: week08acr5678
  ACR_LOGIN_SERVER: week08acr5678.azurecr.io
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./frontend/
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout
        run: az logout
        if: always()
