name: Frontend CI - Build and Push Images to ACR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Frontend
        run: |
          IMAGE_TAG=${{ github.sha }}-${{ github.run_id }}
          ACR=${{ secrets.ACR_LOGIN_SERVER }}

          echo "🚀 Building frontend image..."
          docker build ./frontend -t $ACR/frontend:$IMAGE_TAG

          echo "✅ Pushing versioned tag: $IMAGE_TAG"
          docker push $ACR/frontend:$IMAGE_TAG

          echo "✅ Tagging and pushing 'latest'"
          docker tag $ACR/frontend:$IMAGE_TAG $ACR/frontend:latest
          docker push $ACR/frontend:latest

      - name: Logout
        run: az logout
        if: always()
